using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Exegesis.Shared
{
    /// <summary>
    /// The two things about controller sub-assets that no library does for us.
    /// </summary>
    public static class AnimatorAssets
    {
        /// <summary>
        /// Forces Normalize Blend Values on a blend tree.
        ///
        /// Load-bearing for the whole RCS design: with normalisation OFF a Direct tree SUMS its
        /// children, which is what lets one tree drive several different properties at once,
        /// and lets two children targeting the same property form a lerp (the smoother) or a
        /// signed pair (the IMU). Unity defaults it off, but a grep of all three Animator As
        /// Code packages finds no reference to it whatsoever - AAC will neither set it nor
        /// preserve it, so if the default ever flips, the entire acceleration chain quietly
        /// changes meaning with no error anywhere.
        ///
        /// No public scripting property exposes it, hence SerializedObject.
        /// </summary>
        public static void SetNormalizedBlendValues(BlendTree tree, bool normalized, string logPrefix)
        {
            var so = new SerializedObject(tree);
            var prop = so.FindProperty("m_NormalizedBlendValues");
            if (prop == null)
            {
                Debug.LogWarning($"{logPrefix} Could not find m_NormalizedBlendValues on blend " +
                                 $"tree '{tree.name}'; verify in the Animator window that " +
                                 "Normalize Blend Values is unchecked.");
                return;
            }

            prop.boolValue = normalized;
            so.ApplyModifiedPropertiesWithoutUndo();
        }

        /// <summary>
        /// Destroys every sub-asset of the controller that nothing in it references any more.
        ///
        /// Needed because Animator As Code does not clean up after itself completely.
        /// CreateOrClearLayerAtSameIndex empties a layer by assigning empty arrays over its
        /// states and transitions, which DETACHES those objects without destroying them, and
        /// ClearPreviousAssets only ever removes AnimationClip, BlendTree and AvatarMask - never
        /// an AnimatorState, transition or behaviour. Left alone, a controller regenerated on
        /// every build grows without bound, and this one is committed and reviewed in diffs.
        ///
        /// Reachability rather than name matching, deliberately. AAC's own cleanup keys off the
        /// "zAutogenerated/{AssetKey}__" prefix, which means it stops working the moment a
        /// sub-asset is renamed to something readable - and renaming them is exactly what keeps
        /// the committed controller's diff reviewable. Reachability does not care what anything
        /// is called, so the two concerns stop fighting.
        ///
        /// Only sub-assets of the controller file are considered. Clips that live in their own
        /// .anim files are not returned by LoadAllAssetsAtPath and are never at risk.
        /// </summary>
        public static int SweepUnreachableSubAssets(AnimatorController controller, string logPrefix)
        {
            var path = AssetDatabase.GetAssetPath(controller);
            if (string.IsNullOrEmpty(path)) return 0;

            var reachable = new HashSet<Object>();
            foreach (var layer in controller.layers)
            {
                if (layer.avatarMask != null) reachable.Add(layer.avatarMask);
                Collect(layer.stateMachine, reachable);
            }

            var removed = new List<string>();
            foreach (var sub in AssetDatabase.LoadAllAssetsAtPath(path))
            {
                if (sub == null || sub == controller) continue;
                if (reachable.Contains(sub)) continue;
                if (!IsControllerOwned(sub)) continue;

                removed.Add($"{sub.GetType().Name} '{sub.name}'");
                Object.DestroyImmediate(sub, true);
            }

            if (removed.Count > 0)
            {
                Debug.Log($"{logPrefix} Swept {removed.Count} orphaned sub-asset(s) out of " +
                          $"{path}: {string.Join(", ", removed.Take(12))}" +
                          (removed.Count > 12 ? ", ..." : "") + ".");
            }

            return removed.Count;
        }

        /// <summary>
        /// Every distinct AnimationClip reachable from the layers whose name starts with the
        /// given prefix, including clips nested inside blend trees.
        ///
        /// Scoped by reachability rather than by "every clip sub-asset of the controller",
        /// which is a distinction with teeth: ncho_fx carries two orphaned clips left behind by
        /// an old duplicate-the-controller operation ("Copied from ncho_fx/..."), one of which
        /// legitimately has no curves. Auditing every clip in the file would report that as a
        /// generation failure forever.
        /// </summary>
        public static IEnumerable<AnimationClip> ClipsReachableFrom(AnimatorController controller,
                                                                    string layerPrefix)
        {
            var reachable = new HashSet<Object>();
            foreach (var layer in controller.layers)
            {
                if (layer.name == null || !layer.name.StartsWith(layerPrefix)) continue;
                Collect(layer.stateMachine, reachable);
            }

            return reachable.OfType<AnimationClip>();
        }

        /// <summary>
        /// The types a controller owns as sub-assets. Anything else living in the file was put
        /// there by something other than the animator, and this sweep does not get to guess
        /// about it.
        /// </summary>
        private static bool IsControllerOwned(Object o) =>
            o is AnimatorState ||
            o is AnimatorStateMachine ||
            o is AnimatorTransitionBase ||
            o is StateMachineBehaviour ||
            o is BlendTree ||
            o is AnimationClip ||
            o is AvatarMask;

        private static void Collect(AnimatorStateMachine sm, HashSet<Object> into)
        {
            if (sm == null || !into.Add(sm)) return;

            foreach (var b in sm.behaviours) if (b != null) into.Add(b);
            foreach (var t in sm.anyStateTransitions) if (t != null) into.Add(t);
            foreach (var t in sm.entryTransitions) if (t != null) into.Add(t);

            foreach (var child in sm.states)
            {
                var state = child.state;
                if (state == null) continue;

                into.Add(state);
                foreach (var b in state.behaviours) if (b != null) into.Add(b);
                foreach (var t in state.transitions) if (t != null) into.Add(t);
                Collect(state.motion, into);
            }

            foreach (var child in sm.stateMachines)
            {
                if (child.stateMachine == null) continue;
                foreach (var t in sm.GetStateMachineTransitions(child.stateMachine))
                    if (t != null) into.Add(t);
                Collect(child.stateMachine, into);
            }
        }

        private static void Collect(Motion motion, HashSet<Object> into)
        {
            if (motion == null || !into.Add(motion)) return;
            if (!(motion is BlendTree tree)) return;

            foreach (var child in tree.children) Collect(child.motion, into);
        }
    }
}
