using AnimatorAsCode.V1;
using Exegesis.Shared;
using UnityEditor.Animations;
using UnityEngine;

namespace Exegesis.Aac
{
    /// <summary>
    /// The glue between Animator As Code and this project's destructive, committed-asset model.
    ///
    /// AAC's usual flow is non-destructive: layers are generated at build time through NDMF or
    /// Modular Avatar and never exist in a file. This project does the opposite on purpose - the
    /// generators write into ncho_fx.controller, and the result is committed, diffable and
    /// testable without a scene. Everything here exists to make that work.
    ///
    /// Each helper below documents what breaks without it. None of them is decoration.
    /// </summary>
    public static class ExegesisAac
    {
        /// <summary>
        /// An AAC handle writing into a committed controller.
        ///
        /// AnimatorRoot and DefaultValueRoot are null, and that is verified rather than hopeful:
        /// AnimatorRoot is only ever dereferenced by the Transform, GameObject and Component
        /// clip overloads and by ResolveAvatarMask, none of which are used here, and
        /// DefaultValueRoot is documented as unused in AAC's own source. Leaving them null is
        /// what keeps the generators scene-less, which is what lets them run in the headless
        /// clone.
        ///
        /// ContainerMode must be Everything. With Never, or with a null AssetContainer, AAC
        /// creates clips and blend trees that are never persisted - they survive until the next
        /// domain reload and then every motion in the controller is null.
        ///
        /// AssetKey namespaces the sub-assets AAC creates. The two generators must pass
        /// different keys or each one's cleanup would target the other's assets.
        /// </summary>
        public static AacFlBase Create(AnimatorController container, string systemName, string assetKey)
        {
            return AacV1.Create(new AacConfiguration
            {
                SystemName = systemName,
                AssetKey = assetKey,
                AnimatorRoot = null,
                DefaultValueRoot = null,
                AssetContainer = container,
                ContainerMode = AacConfiguration.Container.Everything,
                DefaultsProvider = new ExegesisDefaultsProvider(),
            });
        }

        /// <summary>
        /// A clip with a stable, readable name.
        ///
        /// AAC names generated sub-assets "zAutogenerated/{AssetKey}__{name}_{random int}", with
        /// the integer drawn fresh on every call. Left as-is, the committed controller's diff
        /// churns on every rebuild even when nothing changed, and reviewing that diff - which is
        /// the entire reason this project keeps a generated asset in git - stops being possible.
        ///
        /// Renaming past AAC's prefix disables its own ClearPreviousAssets, which matches on it.
        /// That is deliberate and safe: cleanup here is done by
        /// AnimatorAssets.SweepUnreachableSubAssets, which works on reachability and does not
        /// care what anything is called. One owner for cleanup, not two.
        /// </summary>
        public static AacFlClip Clip(AacFlBase aac, string name)
        {
            var clip = aac.NewClip(name);
            clip.Clip.name = name;
            return clip;
        }

        /// <summary>
        /// A Direct blend tree that SUMS its children rather than averaging them.
        ///
        /// Two things AAC does not do: it never touches m_NormalizedBlendValues (verified by
        /// grep across all three packages), and unlike its Simple1D constructor it does not set
        /// useAutomaticThresholds on a Direct tree. Both are set here so the tree matches every
        /// other tree in this controller.
        /// </summary>
        public static AacFlBlendTreeDirect DirectTree(AacFlBase aac, string name, string logPrefix)
        {
            var tree = aac.NewBlendTree().Direct();
            tree.BlendTree.name = name;
            tree.BlendTree.useAutomaticThresholds = false;
            AnimatorAssets.SetNormalizedBlendValues(tree.BlendTree, false, logPrefix);
            return tree;
        }

        /// <summary>
        /// A 1D blend tree. AAC already sets useAutomaticThresholds false here; only the name
        /// needs fixing, and for the same reason as Clip above.
        ///
        /// Call FinishTree1D once its children are in - see there for why.
        /// </summary>
        public static AacFlBlendTree1D Tree1D(AacFlBase aac, string name, AacFlFloatParameter parameter)
        {
            var tree = aac.NewBlendTree().Simple1D(parameter);
            tree.BlendTree.name = name;
            return tree;
        }

        /// <summary>
        /// Restores the directBlendParameter Unity would have put on a 1D tree's children.
        ///
        /// Unity's BlendTree.AddChild initialises every child's directBlendParameter to "Blend";
        /// AAC's 1D WithAnimation builds its ChildMotion without touching that field, so it ends
        /// up empty. The field is dead weight on a 1D tree - only Direct trees read it - so this
        /// changes no behaviour whatsoever.
        ///
        /// It is reproduced anyway, because the alternative is worse. Leaving it would put two
        /// dozen meaningless lines into the equivalence diff, and the only way to get a green
        /// result would be to teach the comparison to ignore the field. Ignore-lists are how
        /// real differences end up hiding behind cosmetic ones; a diff that is empty because
        /// nothing differs is worth more than one that is empty because we stopped looking.
        /// </summary>
        public static AacFlBlendTree1D FinishTree1D(AacFlBlendTree1D tree)
        {
            var children = tree.BlendTree.children;
            for (int i = 0; i < children.Length; i++)
            {
                if (string.IsNullOrEmpty(children[i].directBlendParameter))
                    children[i].directBlendParameter = "Blend";
            }
            tree.BlendTree.children = children;
            return tree;
        }

        /// <summary>
        /// Removes every layer whose name starts with the given prefix, destroying the
        /// sub-assets it owned.
        ///
        /// Run BEFORE handing the controller to AAC, so AAC always takes its append-a-new-layer
        /// path rather than its clear-an-existing-one path. The latter empties a layer by
        /// assigning empty arrays over its states and transitions, which detaches those objects
        /// without destroying them and leaks them into the committed file.
        ///
        /// Matching is on PREFIX, not an explicit list of names. An earlier rename in this
        /// project left a layer orphaned in the controller because its old name was no longer in
        /// the list the teardown consulted.
        /// </summary>
        public static void RemoveLayersByPrefix(AnimatorController controller, string prefix)
        {
            var keep = new System.Collections.Generic.List<AnimatorControllerLayer>();
            foreach (var layer in controller.layers)
            {
                if (layer.name == null || !layer.name.StartsWith(prefix))
                {
                    keep.Add(layer);
                    continue;
                }
                DestroyStateMachine(layer.stateMachine);
            }
            controller.layers = keep.ToArray();
        }

        /// <summary>
        /// Removes layers by exact name, returning how many went. Used for hand-built layers a
        /// generator has replaced - a one-way migration that is a no-op after the first run.
        /// </summary>
        public static int RemoveLayersByName(AnimatorController controller, string[] names)
        {
            var keep = new System.Collections.Generic.List<AnimatorControllerLayer>();
            int removed = 0;
            foreach (var layer in controller.layers)
            {
                if (layer.name == null || System.Array.IndexOf(names, layer.name) < 0)
                {
                    keep.Add(layer);
                    continue;
                }
                DestroyStateMachine(layer.stateMachine);
                removed++;
            }
            controller.layers = keep.ToArray();
            return removed;
        }

        private static void DestroyStateMachine(AnimatorStateMachine sm)
        {
            if (sm == null) return;

            // Transitions and behaviours are sub-assets in their own right. Skipping them leaks
            // a handful of orphaned objects into the controller file on every single rebuild -
            // for the loadout layer that is one parameter driver per preset per build.
            foreach (var t in sm.anyStateTransitions) Object.DestroyImmediate(t, true);
            foreach (var t in sm.entryTransitions) Object.DestroyImmediate(t, true);
            foreach (var b in sm.behaviours) if (b != null) Object.DestroyImmediate(b, true);

            foreach (var child in sm.states)
            {
                if (child.state == null) continue;
                foreach (var t in child.state.transitions) Object.DestroyImmediate(t, true);
                foreach (var b in child.state.behaviours) if (b != null) Object.DestroyImmediate(b, true);
                DestroyMotion(child.state.motion);
                Object.DestroyImmediate(child.state, true);
            }

            foreach (var child in sm.stateMachines) DestroyStateMachine(child.stateMachine);
            Object.DestroyImmediate(sm, true);
        }

        private static void DestroyMotion(Motion motion)
        {
            // Blend trees are sub-assets and go. Clips are left to the reachability sweep: with
            // AAC owning clip creation they are now sub-assets too, but they can be SHARED
            // between layers, so destroying one here could take out a motion another layer is
            // still using.
            if (!(motion is BlendTree tree)) return;
            foreach (var child in tree.children) DestroyMotion(child.motion);
            Object.DestroyImmediate(tree, true);
        }
    }
}
